# Copy scripts
cp usr/sbin/xe-set-authorized-keys /usr/sbin/xe-set-authorized-keys
cp usr/sbin/xe-set-hostname /usr/sbin/xe-set-hostname
cp usr/sbin/xe-set-network /usr/sbin/xe-set-network
cp usr/sbin/generate-sshd-keys /usr/sbin/generate-sshd-keys
cp etc/init.d/xe-automator.sh /etc/init.d/xe-automator.sh
chmod a+x /usr/sbin/xe-set-authorized-keys
chmod a+x /usr/sbin/xe-set-hostname
chmod a+x /usr/sbin/xe-set-network
chmod a+x /usr/sbin/generate-sshd-keys
update-rc.d /etc/init.d/xe-automator.sh defaults
